/**
 * Two-sentence hover blurbs for control-room tiles, gauges, and lights.
 * Describes what each series measures. No forecasts, no invented prints.
 */
window.ECR_EXPLAIN = {
  spx: "The S&P 500 is a market-cap-weighted index of about 500 large U.S. companies. It is the usual yardstick for U.S. large-cap equity prices.",
  nasdaq: "The Nasdaq Composite tracks almost all stocks listed on the Nasdaq exchange. It is heavy in technology and growth names, so it moves with those sectors.",
  dow: "The Dow Jones Industrial Average is a price-weighted index of 30 large U.S. blue-chip companies. It is a narrow snapshot of big industrial and consumer names, not the whole market.",
  vix: "The VIX is the market's implied 30-day volatility on the S&P 500. A high reading means traders are paying up for protection and expect larger swings.",
  dax: "The DAX is a blue-chip index of major companies listed in Germany. It is a common stand-in for German and euro-area equity prices.",
  eem: "EEM is an ETF that holds a basket of emerging-market stocks. Its price tracks those markets in U.S. dollars.",

  tnx: "This is the yield on the 10-year U.S. Treasury note. It is the benchmark long-term interest rate that feeds into mortgages, corporate borrowing, and discount rates.",
  tyx: "This is the yield on the 30-year U.S. Treasury bond. It measures the cost of very long-term government borrowing.",
  fvx: "This is the yield on the 5-year U.S. Treasury note. It sits in the middle of the curve and is sensitive to the expected path of policy over the next few years.",
  irx: "This is the discount yield on the 13-week U.S. Treasury bill. It is a short-term government rate that tracks the policy stance closely.",
  twoy: "This is the yield on the 2-year U.S. Treasury note. It is tightly linked to expected Fed policy over the near term.",
  tlt: "TLT is an ETF of long-duration U.S. Treasuries, mostly 20 years and longer. Its price rises when long yields fall and falls when long yields rise.",
  hyg: "HYG is an ETF of U.S. high-yield (junk) corporate bonds. Its price reflects both credit spreads and the level of interest rates.",
  lqd: "LQD is an ETF of U.S. investment-grade corporate bonds. It measures the market value of higher-quality company debt.",
  spread_2s10s: "The 2s10s spread is the 10-year Treasury yield minus the 2-year yield. A positive number is an upward-sloping curve; a negative number means the curve is inverted.",
  spread_3m10s: "The 3m10s spread is the 10-year Treasury yield minus the 3-month bill yield. This tile reports that gap only; it is not a recession probability.",
  fedfunds: "The federal funds rate is the overnight rate banks charge each other for reserves. It is the Federal Reserve's main policy rate.",
  hy_oas: "HY OAS is the option-adjusted spread of the ICE BofA U.S. high-yield index over Treasuries. A wider spread means junk borrowers are paying more extra yield for credit risk.",
  nfci: "The Chicago Fed National Financial Conditions Index summarizes money, credit, and leverage conditions. Readings below zero are looser than average; readings above zero are tighter.",

  dxy: "The U.S. Dollar Index measures the dollar against a basket of major currencies, led by the euro. A higher reading means a stronger dollar on that basket.",
  gold: "This is the nearby price of gold in U.S. dollars per troy ounce. Gold is a traded monetary metal, not a claim on a company's earnings.",
  silver: "This is the nearby price of silver in U.S. dollars per troy ounce. Silver is both a monetary metal and an industrial input.",
  platinum: "This is the nearby price of platinum in U.S. dollars per troy ounce. Platinum is used in auto catalysts and industry as well as jewelry.",
  copper: "This is the nearby price of copper in U.S. dollars per pound. Copper is a core industrial metal used in construction, wiring, and manufacturing.",
  wti: "WTI is the U.S. benchmark crude-oil futures price, in dollars per barrel. It is the usual quote for American light sweet crude.",
  brent: "Brent is the main international crude-oil benchmark, in dollars per barrel. It prices a large share of seaborne oil.",
  natgas: "This is the U.S. Henry Hub natural-gas futures price, in dollars per million Btu. It is the benchmark for North American gas.",
  btc: "Bitcoin is a traded cryptocurrency; this is its price in U.S. dollars. The print is a market price, not a claim on output or earnings.",
  eth: "Ethereum is a traded cryptocurrency; this is its price in U.S. dollars. The print is a market price, not a claim on output or earnings.",

  gdp_usa: "World Bank annual real GDP growth for the United States. It is a lagged yearly figure, not the quarterly BEA print.",
  gdp_wld: "World Bank annual real GDP growth for the world as a whole. It averages advanced and emerging economies on a yearly basis.",
  gdp_euu: "World Bank annual real GDP growth for the European Union. It is a lagged yearly figure for the bloc.",
  gdp_chn: "World Bank annual real GDP growth for China. It is a lagged yearly figure, not a quarterly official print.",
  gdp_jpn: "World Bank annual real GDP growth for Japan. It is a lagged yearly figure for the Japanese economy.",
  gdp_us_q: "This is the BEA's quarterly real GDP growth for the United States, annualized (SAAR). It is the standard high-frequency read on U.S. output.",

  uem_usa: "World Bank annual unemployment rate for the United States. It is a lagged yearly figure, not the monthly BLS U-3 print.",
  uem_wld: "World Bank annual unemployment rate for the world. It is a coarse yearly average across countries.",
  uem_euu: "World Bank annual unemployment rate for the European Union. It is a lagged yearly figure for the bloc.",
  uem_chn: "World Bank annual unemployment rate for China. It is a lagged yearly figure and uses the Bank's definition.",
  unrate: "U-3 is the official U.S. unemployment rate from the BLS household survey. It is the share of the labor force that is jobless and actively looking.",
  icsa: "Initial jobless claims count people filing for unemployment insurance for the first time in a week. It is a timely read on layoffs, not the unemployment rate itself.",
  nrou: "NROU is the CBO's estimate of the natural rate of unemployment. It is a model of the jobless rate consistent with stable inflation, not a survey print.",
  u_gap_nrou: "This is the official U-3 unemployment rate minus the CBO natural rate (NROU). A positive gap means joblessness is above that estimate; a negative gap means it is below.",

  cpi: "This is the year-over-year change in the U.S. consumer price index (CPI-U). It is the usual headline measure of what households pay for a fixed basket of goods and services.",
  cpi_usa_wb: "World Bank annual consumer-price inflation for the United States. It is a lagged yearly figure, not the monthly BLS CPI print.",
  t5yifr: "The 5y5y forward inflation rate is the market's implied average CPI inflation from five years from now for the following five years. It is read from TIPS and nominal Treasuries, not a survey.",
  ppi: "This is the year-over-year change in the producer price index for all commodities. It tracks prices at the wholesale and commodity stage, before they fully show up in consumer prices.",
  ppi_cpi_spread: "This is PPI year-over-year minus CPI year-over-year. A positive number means producer prices are rising faster than consumer prices; a negative number means the reverse.",

  m2: "M2 is the Federal Reserve's broad money stock: currency, checking, savings, and small time deposits, plus retail money funds. It is a stock of money, not a flow of spending.",
  m2_yoy: "This is the year-over-year percent change in M2. It is a growth-rate lens on the broad money stock.",
  m2v: "M2 velocity is nominal GDP divided by M2. It measures how many times the money stock turns over in a year of spending.",
  real_m2: "Real M2 growth is M2's year-over-year change after subtracting CPI inflation. It asks whether the money stock is growing faster or slower than consumer prices.",
  base: "The monetary base is currency in circulation plus reserve balances at the Fed. It is the narrowest official money stock, often called high-powered money.",
  base_yoy: "This is the year-over-year percent change in the monetary base. It shows how fast high-powered money is expanding or shrinking.",
  totll: "Total loans and leases at commercial banks, from the Fed's H.8 release. It is the outstanding stock of bank credit to households and firms.",
  busloans: "Commercial and industrial loans at commercial banks. This is the stock of bank credit extended to businesses for operating and investment needs.",
  loans_yoy: "This is the year-over-year percent change in total bank loans and leases. Fast growth means credit is expanding; contraction means banks are pulling back.",
  money_multiplier: "The money multiplier here is M2 divided by the monetary base. It is a simple ratio of broad money to high-powered money, not a forecast of lending.",
  excess_money: "Excess money is M2 year-over-year growth minus nominal GDP year-over-year growth. A positive reading means the money stock is growing faster than spending; a negative reading means the reverse.",
  tdsp: "The household debt-service ratio is required mortgage and consumer-debt payments as a share of disposable income. It measures how much of household income is spoken for by existing debt.",
  credit_gdp: "This is total credit-market debt outstanding divided by nominal GDP. It is a stock-to-flow ratio: how many years of current output the debt pile represents.",
  walcl_t: "This is the Federal Reserve's total assets (WALCL) expressed in trillions of dollars. It is the size of the Fed's balance sheet, not a policy-rate setting.",

  houst: "Housing starts count new privately owned housing units begun, at a seasonally adjusted annual rate. It is a timely read on residential construction activity.",
  indpro: "The industrial production index covers manufacturing, mining, and utilities output. It measures physical production, not prices or employment.",
  ipcongd: "This is the industrial production index for consumer goods. It tracks factory output of things households buy, not materials further up the chain.",
  ipmat: "This is the industrial production index for materials. It tracks output of intermediate goods used to make other goods.",
  higher_order_ratio: "This is materials industrial production divided by consumer-goods industrial production. A higher ratio means more activity in earlier (higher-order) stages of production relative to consumer goods.",

  real_policy_rate: "The real policy rate is the federal funds rate minus year-over-year CPI inflation. It is a rough measure of how tight or easy policy is after prices.",
  copper_gold: "This is the copper price divided by the gold price, scaled by 1,000. It is a relative-price ratio of an industrial metal to a monetary metal.",
  gold_silver: "This is the gold price divided by the silver price, in ounces of silver per ounce of gold. It is a relative-price ratio of the two monetary metals.",
  output_gap: "The output gap here is real GDP (GDPC1) relative to CBO potential GDP (GDPPOT), as a percent. A positive gap means actual output is above that estimate of potential; a negative gap means it is below.",
  taylor_implied: "This is the federal funds rate implied by the 1993 Taylor rule using current inflation and the output gap. It is a constructed rule-of-thumb, not a Fed announcement.",
  taylor_gap: "The Taylor gap is the actual federal funds rate minus that 1993 Taylor-rule implied rate. A positive number means policy is tighter than the rule; a negative number means it is easier.",
  sahm: "The Sahm rule is the three-month average unemployment rate minus its low over the prior twelve months. It is a real-time labor-market deterioration gauge, not a forecast model.",

  // Headline / pressure / money gauge keys (same idea as the preferred FRED series)
  gdp: "This is the BEA's quarterly real GDP growth for the United States, annualized (SAAR). It is the standard high-frequency read on U.S. output.",
  unemp: "U-3 is the official U.S. unemployment rate from the BLS household survey. It is the share of the labor force that is jobless and actively looking.",
  inflation: "This is the year-over-year change in the U.S. consumer price index (CPI-U). It is the usual headline measure of what households pay for a fixed basket of goods and services.",
  policy: "The federal funds rate is the overnight rate banks charge each other for reserves. It is the Federal Reserve's main policy rate.",
  real_policy: "The real policy rate is the federal funds rate minus year-over-year CPI inflation. It is a rough measure of how tight or easy policy is after prices.",

  // Light aliases (same series; extra keys for invert / claims / rule names)
  invert: "The 3m10s spread is the 10-year Treasury yield minus the 3-month bill yield. This light trips when that gap is negative (an inverted curve).",
  claims: "Initial jobless claims count people filing for unemployment insurance for the first time in a week. This light trips when weekly claims are elevated.",
  taylor: "The Taylor gap is the actual federal funds rate minus the 1993 Taylor-rule implied rate. This light trips when the gap is large in either direction.",
  "k-percent": "This is the year-over-year percent change in M2. The K-percent light trips when money growth is far from a steady path.",
  k_percent: "This is the year-over-year percent change in M2. The K-percent light trips when money growth is far from a steady path.",
  credit_boom: "This is the year-over-year percent change in total bank loans and leases. The credit-boom light trips when loan growth is running very fast.",
  debt_service: "The household debt-service ratio is required mortgage and consumer-debt payments as a share of disposable income. This light trips when that burden is high."
};
